### PR TITLE
livekit: send mute events to SFU

### LINKED ISSUE #358: Not receiving `TrackMuted` or `ActiveSpeakersChanged` events
In my simple test app, I do not seem to receive events about muting, unmuting, or active speakers changing. Is there anything I need to opt into in order to receive these events?

To reproduce in a fairly minimal test app, checkout [this branch](https://github.com/zed-industries/zed/pull/13343) of Zed, and run 

```
cargo run -p live_kit_client --example test_app
```

It connects to a live kit server on the default port, 7880.

### PR DESCRIPTION
**Pull request by nbsp**
fixes #358 (`ActiveSpeakersChanged` always got sent for me, this fixes the `Muted` issues)

tested with Zed's example, with rust-sdks on commit `ffi-v0.6.1~3` because some APIs changed since they made the example.

### CODE REVIEW

File: livekit/src/room/participant/mod.rs [hunk 1]
```diff
@@ -248,8 +248,19 @@ pub(super) fn add_publication(
     publication.on_muted({
         let events = inner.events.clone();
         let participant = participant.clone();
+        let rtc_engine = inner.rtc_engine.clone();
         move |publication| {
             if let Some(cb) = events.track_muted.lock().as_ref() {
+                let rtc_engine = rtc_engine.clone();
```
Comment (theomonnom) [inline livekit/src/room/participant/mod.rs]: When unmuting or muting again, there is no guarantee that these tasks will run in order. Seems like a race could happen here?

File: livekit/src/room/participant/mod.rs
Comment (theomonnom) [inline livekit/src/room/participant/mod.rs:1]: We should only send MuteTrackRequest for local tracks. This is sending mute requests even for remote tracks

File: livekit/src/room/participant/mod.rs (hunk 1 above)
Comment (nbsp) [reply livekit/src/room/participant/mod.rs]: as in the `mute_track().await` could take longer then the unmute after it?

File: livekit/src/room/participant/mod.rs
Comment (nbsp) [reply livekit/src/room/participant/mod.rs:1]: added an if clause, this still runs on `Participant` just because of the way the `TrackPublication` gets passed inside a function so we can't access it until we run it

File: livekit/src/room/participant/mod.rs (hunk 1 above)
Comment (theomonnom) [reply livekit/src/room/participant/mod.rs]: not necessarily longer, but the unmute could be executed before the mute request

Comment (nbsp) [reply livekit/src/room/participant/mod.rs]: new commit locks mute and unmute under the same mutex

File: livekit/src/room/participant/mod.rs [hunk 2]
```diff
@@ -248,8 +248,21 @@ pub(super) fn add_publication(
...
         let events = inner.events.clone();
         let participant = participant.clone();
+        let rtc_engine = inner.rtc_engine.clone();
         move |publication| {
             if let Some(cb) = events.track_muted.lock().as_ref() {
+                if !publication.is_remote() {
+                    let rtc_engine = rtc_engine.clone();
+                    let publication_cloned = publication.clone();
+                    livekit_runtime::spawn(async move {
+                        let _ = rtc_engine
```
Comment (theomonnom) [inline livekit/src/room/participant/mod.rs]: I don't think we should ignore the error here

File: livekit/src/room/participant/mod.rs (hunk 1 above)
Comment (theomonnom) [reply livekit/src/room/participant/mod.rs]: I saw you added the mutex, but this isn't fixing the issue. The race could still be there

File: livekit/src/room/participant/mod.rs (hunk 2 above)
Comment (theomonnom) [reply livekit/src/room/participant/mod.rs]: Same as the other PR. We should log instead of returning inside the tokio task

**Review by theomonnom — APPROVED** [review]
